Dockerfile
praetorian-inc/noseyparker pull request #1
Opened 2022-12-08 20:28 UTC by DS-KoolAid

Adding Dockerfile and the associated documentation to the README.md

2022-12-08 21:14 UTC, bradlarsen requested changes
Thanks @DS-KoolAid! Great contribution. I like the multi-stage build approach, which should leave us with a pretty small final image to actually run.

I will merge this after a couple Docker nits are addressed. I suggested a couple fixes that I think you could just click to apply -- I hope I spelled them right.

2022-12-08 21:14 UTC, bradlarsen commented on Dockerfile
> +RUN apt install build-essential libhyperscan-dev pkg-config git -y
You'll want to combine these two lines into a single `RUN` command for this to behave as expected with Docker caching. See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

```suggestion
RUN apt update && apt install -y \
    build-essential \
    libhyperscan-dev \
    pkg-config git
```

2022-12-08 21:14 UTC, bradlarsen commented on Dockerfile
> +RUN apt install libhyperscan-dev -y
You'll want to combine these two lines into a single `RUN` command for this to behave as expected with Docker caching. See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

```suggestion
RUN apt update && apt install -y \
    libhyperscan-dev
```

2022-12-09 00:14 UTC, DS-KoolAid commented
Changes committed!

2022-12-09 00:29 UTC, bradlarsen approved these changes

2022-12-09 00:30 UTC, merged